### ISSUE TITLE
Accepting contributions to all UI/Design enhancements 

### ISSUE THREAD

**Issue by vimark1** [vimark1/typist#115]
We've just put together the app without much thought on Design/UX.
Accepting any improvement PRs in that area, Thanks!

**Comment by TimeForJakob** [comment]
Have you got anything special in mind? Or any idea what you particularly don't like about the current design?

**Comment by vimark1** [comment]
Hi @TimeForJakob.  I think anything is an improvement from the current state

**Comment by TimeForJakob** [comment]
Okay so i made a few tweaks:

1. I added the "event-stream" npm package to the package.json file, because 'npm install' threw an E404 error that that specific package wasn't found

2. I changed the links to a smoother hover effect and made the active tabs a bit prettier than green background with white text

3. I put the "Please log in to save score" error above the typing text, but I would personally consider some kind of button for saving the score, so that the error just appears once the user want's to actually save the score and is not shown all the time.
I didn't implement this in the current version, because I've had too little time lately to really go through the project and look at all the mechanics the the internal lifecycle.

It is no big improvement whatsoever, but i just wanted to fix those little things that disturbed me when I looked at the app in the first place.
