### ISSUE TITLE
Score Leaderboard

### ISSUE THREAD

**Issue by smkamranqadri** [vimark1/typist#29]
A score leaderboard showing top 10 scores. For now three basic info need to be shown, rank, name or email, and score.

We will need to write firebase cloud function on every score update to analysis if the score is in between the highest and lowest score at that time.

For that, we need to maintain a node top-score, which will have three child node, highest score, lowest score and top-10 score.

**Comment by rahul1995** [comment]
Added basic scoreboard here at this PR: https://github.com/vimark1/typist/pull/67 
I didn't add CSS, and I am using only one node to keep top 10 scores (instead of 3 nodes), and whenever a new score is saved, I just add it to the top 10 scores list, sort it and slice the top 10 ones and persist into database.

**Comment by vimark1** [comment]
@rahul1995 thanks for the PR, it's just a start of it, going forward we probably dont want to set the whole top-scorers collection every time as that will cause a race conditions if another user is storing the data at the same time

**Comment by vimark1** [comment]
Merged in #67

**Comment by rahul1995** [comment]
@vimark1 I didn't think about the race condition. Race condition will always occur if we let two users read database same time to add their scores in the list. 
We need some sort of synchronization in it. I'll try to investigate more through firebase.
