### ISSUE TITLE
integrate with Firebase

### ISSUE THREAD

**Issue by fpereira1** [vimark1/typist#6]
add firebase login
store scores for logged in user in Firebase

**Comment by smkamranqadri** [comment]
I'll take this.

**Comment by vimark1** [comment]
Hi @smkamranqadri - thank you for your contribution! post here if you have any thoughts or questions about this enhancement

**Comment by smkamranqadri** [comment]
Have finished the auth part, now little bit confuse with the store part, which score needs to store? word per minute and if which one, last one or average of the session?

**Comment by smkamranqadri** [comment]
I really like this app, want to work more on it, let's connect on any messaging platform to discuss further,

**Comment by vimark1** [comment]
hey @smkamranqadri - that is awesome!  I look forward to reviewing your changes.

> now little bit confuse with the store part, which score needs to store? word per minute and if which one, last one or average of the session?

The array that gets build as you complete each session is your score, ie words per minute.
we should store that value so later we can build graphs with that data and users will see how they are improving, ideally we should store: wpm, timestamp

Later on I'd like to store all the letters that appear so that we can build a heatmap of which keys are being used the most

> I really like this app, want to work more on it, let's connect on any messaging platform to discuss further,

That is great.  Feature requests and contributions are definitely welcome.  If you have any thoughts or ideas about the app, please create an issue, even better, send a pull request regarding your new feature or bug fixes and we'll be glad to review and merge it.

I will setup a gitter chat for the project. also check  your invites, I've made you a contributor on this project.

Thanks!

**Comment by vimark1** [comment]
Gitter chat https://gitter.im/vimark1-typist/Lobby

**Comment by vimark1** [comment]
The initial integration with Firebase has been merged
